// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'active': string;
  'arrow': string;
  'burger': string;
  'label': string;
  'link': string;
  'list': string;
  'logo': string;
  'navItem': string;
  'navigation': string;
  'opened': string;
  'poweredBy': string;
  'sub': string;
  'visible': string;
}
declare var cssExports: CssExports;
export = cssExports;
