// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'hljs-attr': string;
  'hljs-literal': string;
  'hljs-number': string;
  'hljs-tag': string;
  'hljs-template-variable': string;
  'hljs-variable': string;
}
declare var cssExports: CssExports;
export = cssExports;
