// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'addVideo': string;
  'form-control': string;
  'title': string;
}
declare var cssExports: CssExports;
export = cssExports;
