// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'Audio': string;
  'againBtn': string;
  'audioList': string;
  'audioPlayer': string;
  'bar': string;
  'btnZone': string;
  'centerAudio': string;
  'leftControls': string;
  'pageAudio': string;
  'playIt': string;
  'progress': string;
  'rightControls': string;
  'time': string;
  'up': string;
  'volume': string;
}
declare var cssExports: CssExports;
export = cssExports;
