// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'ChannelAct': string;
  'areaMessage': string;
  'btn-primary': string;
  'channelItem': string;
  'deleteBtn': string;
  'glyphicon-one-fine-empty-dot': string;
  'glyphicon-one-fine-green-dot': string;
  'mainChat': string;
  'messComposer': string;
  'messDate': string;
  'messItem': string;
  'message': string;
  'nav': string;
  'navChat': string;
  'pageChat': string;
  'react': string;
  'title': string;
  'userName': string;
}
declare var cssExports: CssExports;
export = cssExports;
