// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'dropzone': string;
  'dz-clickable': string;
  'dz-complete': string;
  'dz-details': string;
  'dz-drag-hover': string;
  'dz-error': string;
  'dz-error-mark': string;
  'dz-error-message': string;
  'dz-file-preview': string;
  'dz-filename': string;
  'dz-image': string;
  'dz-image-preview': string;
  'dz-message': string;
  'dz-preview': string;
  'dz-processing': string;
  'dz-progress': string;
  'dz-remove': string;
  'dz-size': string;
  'dz-started': string;
  'dz-success': string;
  'dz-success-mark': string;
  'dz-upload': string;
  'passing-through': string;
  'pulse': string;
  'slide-in': string;
}
declare var cssExports: CssExports;
export = cssExports;
