// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'btnSearch': string;
  'imageItem': string;
  'item': string;
  'itemButtons': string;
  'itemInfo': string;
  'itemLink': string;
  'itemList': string;
  'itemName': string;
  'itemSelect': string;
  'itemprop': string;
  'itemsSelect': string;
  'searchCont': string;
  'simle': string;
  'simple': string;
  'status': string;
}
declare var cssExports: CssExports;
export = cssExports;
