// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'act': string;
  'formInp': string;
  'selects': string;
}
declare var cssExports: CssExports;
export = cssExports;
