// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'audioList': string;
  'audioPart': string;
  'btnZone': string;
  'imagePart': string;
  'imagesPart': string;
  'itemContent': string;
  'itemImage': string;
  'itemInfo': string;
  'itemParams': string;
  'name': string;
  'namePart': string;
  'offline': string;
  'online': string;
  'pageProfile': string;
  'param': string;
  'paramLabel': string;
  'part': string;
  'picturesItem': string;
  'statusItem': string;
  'title': string;
  'video': string;
  'videoPart': string;
}
declare var cssExports: CssExports;
export = cssExports;
