// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'btnVideo': string;
  'pageVideo': string;
  'react-player': string;
  'video': string;
  'videoPart': string;
}
declare var cssExports: CssExports;
export = cssExports;
