// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'blockquote': string;
  'eyebrow': string;
  'first': string;
  'last': string;
  'quoteIcon': string;
  'small': string;
  'subtitle': string;
  'text': string;
  'textCenter': string;
  'textLeft': string;
  'textRight': string;
}
declare var cssExports: CssExports;
export = cssExports;
