// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'active': string;
  'tabButton': string;
  'tabContent': string;
  'tabList': string;
  'tabListItem': string;
  'tabsWrapper': string;
  'wrap': string;
}
declare var cssExports: CssExports;
export = cssExports;
