// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'contentPusher': string;
  'visible': string;
}
declare var cssExports: CssExports;
export = cssExports;
