
export const AUTH_CHOOSE_PICTURE = 'CHOOSE_PICTURE'

export const AUTH_LOAD = 'AUTH_LOAD'
export const AUTH_LOAD_SUCCESS = 'AUTH_LOAD_SUCCESS'
export const AUTH_LOAD_FAIL = 'AUTH_LOAD_FAIL'

export const AUTH_SIGNIN = 'AUTH_SIGNIN'
export const AUTH_SIGNIN_SUCCESS = 'AUTH_SIGNIN_SUCCESS'
export const AUTH_SIGNIN_FAIL = 'AUTH_SIGNIN_FAIL'

export const AUTH_SIGNOUT = 'AUTH_SIGNOUT'
export const SAVE_USERNAME = 'SAVE_USERNAME'
export const AUTH_SIGNOUT_SUCCESS = 'AUTH_SIGNOUT_SUCCESS'
export const AUTH_SIGNOUT_FAIL = 'AUTH_SIGNOUT_FAIL'
export const RECEIVE_SOCKET = 'RECEIVE_SOCKET'

export const AUTH_SIGNUP_SUCCESS = 'AUTH_SIGNUP_SUCCESS'
export const AUTH_SIGNUP = 'AUTH_SIGNUP'
export const AUTH_SIGNUP_FAIL = 'AUTH_SIGNUP_FAIL'
