export const ADD = 'ADD'
export const DEL_ITEM = 'DEL_ITEM'
export const UPDATE_ITEM = 'UPDATE_ITEM'
export const LEAVE_ITEM = 'LEAVE_ITEM'
export const IN_ITEM = 'IN_ITEM'
export const GET_ITEMS = 'GET_ITEMS'
export const GET_ITEM = 'GET_ITEM'
export const FULL_SEARCH = 'FULL_SEARCH'

export const GET_FILES = 'GET_FILES'
export const GET_PICTURES = 'GET_PICTURES'
export const GET_MUSIC = 'GET_MUSIC'
export const REMOVE_FILE = 'REMOVE_FILE'
export const GET_VIDEO = 'GET_VIDEO'
export const ADD_VIDEO = 'ADD_VIDEO'
export const DEL_VIDEO = 'DEL_VIDEO'

export const LIST = 'LIST'
export const STOP = 'STOP'
export const PAUSE = 'PAUSE'
export const CHOOSE = 'CHOOSE'
export const INC_VOLUME = 'INC_VOLUME'
export const DEC_VOLUME = 'DEC_VOLUME'
export const ON = 'ON_ITEM'
export const OFF = 'OFF_ITEM'
