// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'alignItems-center': string;
  'alignItems-flex-end': string;
  'alignItems-flex-start': string;
  'justifyContent-center': string;
  'justifyContent-space-around': string;
  'justifyContent-space-between': string;
  'row': string;
}
declare var cssExports: CssExports;
export = cssExports;
