// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'bounce': string;
  'bubble1': string;
  'bubble2': string;
  'inner': string;
  'loading': string;
  'loadingI': string;
  'spinner': string;
}
declare var cssExports: CssExports;
export = cssExports;
